# Generated by Django 4.2.1 on 2023-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenmembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kenmem',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kenmem',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
